-- mint info : 초대제 회원가입 + 관리자 초대코드 시스템
-- Supabase SQL Editor에서 전체 실행하세요.
-- 실행이 끝나면 마지막 SELECT 결과에 '최초 관리자용 초대 코드'가 표시됩니다.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null default 'new user',
  username text not null unique,
  bio text not null default '',
  theme jsonb not null default '{"background":"#fff3f8","accent":"#ff7bac"}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.invite_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  kind text not null default 'user' check (kind in ('user','bootstrap_admin')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  used_at timestamptz,
  used_by uuid references auth.users(id) on delete set null
);

alter table public.profiles enable row level security;
alter table public.admins enable row level security;
alter table public.invite_codes enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admins
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read"
on public.profiles
for select
to anon, authenticated
using (true);

drop policy if exists "profiles owner update" on public.profiles;
create policy "profiles owner update"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "admins read self" on public.admins;
create policy "admins read self"
on public.admins
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "invite admins read" on public.invite_codes;
create policy "invite admins read"
on public.invite_codes
for select
to authenticated
using (public.is_admin());

create or replace function public.create_invite_code(p_expires_days integer default 7)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_expires timestamptz;
begin
  if not public.is_admin() then
    raise exception 'ADMIN_ONLY';
  end if;

  if p_expires_days is null then
    v_expires := null;
  else
    if p_expires_days < 1 or p_expires_days > 3650 then
      raise exception 'INVALID_EXPIRES_DAYS';
    end if;
    v_expires := now() + make_interval(days => p_expires_days);
  end if;

  loop
    v_code := 'MINT-' || upper(substr(encode(gen_random_bytes(8), 'hex'), 1, 12));
    begin
      insert into public.invite_codes(code, kind, created_by, expires_at)
      values (v_code, 'user', auth.uid(), v_expires);
      exit;
    exception when unique_violation then
      -- 충돌 시 다시 생성
    end;
  end loop;

  return v_code;
end;
$$;

revoke all on function public.create_invite_code(integer) from public;
grant execute on function public.create_invite_code(integer) to authenticated;

-- 회원가입 시 초대 코드를 서버(DB 트리거)에서 검증하고 즉시 1회 사용 처리합니다.
-- 프론트엔드 검증만 사용하는 방식이 아니므로 개발자도구로 일반 가입을 우회할 수 없습니다.
create or replace function public.handle_invited_signup()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_invite text;
  v_nickname text;
  v_kind text;
  v_username text;
begin
  v_invite := upper(trim(coalesce(new.raw_user_meta_data ->> 'invite_code', '')));
  v_nickname := trim(coalesce(new.raw_user_meta_data ->> 'nickname', 'new user'));
  v_username := lower(trim(coalesce(new.raw_user_meta_data ->> 'username', '')));

  if v_invite = '' then
    raise exception 'INVITE_CODE_REQUIRED';
  end if;

  -- 사이트 주소 이름 규칙:
  -- 3~30자 / 영문 소문자, 숫자, 하이픈(-) 허용
  -- 하이픈으로 시작하거나 끝나는 것은 금지 / 공백, 한글, 대문자, 기타 특수문자 금지
  if v_username !~ '^[a-z0-9](?:[a-z0-9-]{1,28}[a-z0-9])?$' then
    raise exception 'INVALID_SITE_NAME';
  end if;

  if v_username = any(array[
    'admin','administrator','root','login','logout','signup','register',
    'dashboard','profile','settings','support','help','api','www',
    'mint','mintinfo'
  ]) then
    raise exception 'RESERVED_SITE_NAME';
  end if;

  if exists (
    select 1 from public.profiles p where p.username = v_username
  ) then
    raise exception 'SITE_NAME_ALREADY_TAKEN';
  end if;

  -- 유효한 초대 코드 1회 사용 처리
  update public.invite_codes
     set used_at = now(),
         used_by = new.id
   where code = v_invite
     and used_at is null
     and (expires_at is null or expires_at > now())
  returning kind into v_kind;

  if v_kind is null then
    raise exception 'INVALID_OR_USED_INVITE_CODE';
  end if;

  insert into public.profiles(id, nickname, username)
  values (
    new.id,
    case when v_nickname = '' then 'new user' else left(v_nickname, 30) end,
    v_username
  );

  if v_kind = 'bootstrap_admin' then
    insert into public.admins(user_id) values (new.id)
    on conflict do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_invited on auth.users;
create trigger on_auth_user_created_invited
after insert on auth.users
for each row execute function public.handle_invited_signup();

-- 최초 1명만 관리자가 될 수 있도록 부트스트랩 코드를 1개 생성합니다.
-- 이 코드를 가장 먼저 '본인 계정' 가입에 사용하세요.
-- 사용 즉시 관리자 계정이 되고, 코드는 다시 사용할 수 없습니다.
insert into public.invite_codes(code, kind, expires_at)
select
  'ADMIN-' || upper(substr(encode(gen_random_bytes(8), 'hex'), 1, 12)),
  'bootstrap_admin',
  now() + interval '1 day'
where not exists (
  select 1 from public.invite_codes where kind = 'bootstrap_admin'
);

select code as "최초 관리자용 초대 코드"
from public.invite_codes
where kind = 'bootstrap_admin'
  and used_at is null
order by created_at asc
limit 1;
